version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image:  circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run: echo "Build process is started"
      - run:
          name: Initial build
          command: ./gradlew clean assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

      - deploy:
          name: "Deploy to Fabric"
          command: |
            echo "Run gradle task to upload generated APK to Fabric"