workflows:
  version: 2
  main:
    jobs:
      - build:
          working_directory: ~/code
          docker:
              - image:  circleci/android:api-29-node
          environment:
            JVM_OPTS: -Xmx4G
          steps:
            - checkout
            - run: echo "Build process is started"
            - run:
                name: Initial build
                command: ./gradlew clean assembleRelease
            - store_artifacts:
                path: app/build/outputs/apk/
                destination: apks/
      - publish-github-release:
          docker:
            - image: circleci/golang:1.8
          steps:
            - attach_workspace:
                at: ./artifacts
            - run:
                name: "Publish Release on GitHub"
                command: |
                  go get github.com/tcnksm/ghr
                  VERSION=$(my-binary --version)
                  ghr -t ${TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
